# Generated by Django 3.0.8 on 2020-07-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitrab2s_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
