# Generated by Django 3.0.8 on 2020-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrab2s_app', '0003_auto_20200722_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='upvote',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='answer_text',
            field=models.CharField(default=1, help_text='Write your text here ..', max_length=200),
            preserve_default=False,
        ),
    ]
