# Generated by Django 3.0.8 on 2020-07-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitrab2s_app', '0006_auto_20200722_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='user_id',
        ),
    ]
